//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGANHANG.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-B60UFJ89\\MSSQLSERVER08;Initial Catalog=NGANHANG;User ID=sa;Pas" +
            "sword=123456")]
        public string NGANHANGConnectionString {
            get {
                return ((string)(this["NGANHANGConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-B60UFJ89\\MSSQLSERVER10;Initial Catalog=NGANHANG;User ID=sa;Pas" +
            "sword=123456")]
        public string NGANHANG_TANDINH {
            get {
                return ((string)(this["NGANHANG_TANDINH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-B60UFJ89\\MSSQLSERVER11;Initial Catalog=NGANHANG;User ID=sa;Pas" +
            "sword=123456")]
        public string NGANHANG_TRACUU {
            get {
                return ((string)(this["NGANHANG_TRACUU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-B60UFJ89\\MSSQLSERVER09;Initial Catalog=NGANHANG;User ID=sa;Pas" +
            "sword=123456")]
        public string NGANHANG_BENTHANH {
            get {
                return ((string)(this["NGANHANG_BENTHANH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-B60UFJ89\\MSSQLSERVER09;Initial Catalog=NGANHANG;User ID=sa;Pas" +
            "sword=123456")]
        public string NGANHANGConnectionString1 {
            get {
                return ((string)(this["NGANHANGConnectionString1"]));
            }
        }
    }
}
